package uy.gub.dgiRecepcion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-12-15T14:13:42.803-03:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "WS_eFactura",
                  wsdlLocation = "https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl",
                  targetNamespace = "http://dgi.gub.uy")
public class WSEFactura extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dgi.gub.uy", "WS_eFactura");
    public final static QName WSEFacturaSoapPort = new QName("http://dgi.gub.uy", "WS_eFacturaSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("https://efactura.dgi.gub.uy:6443/ePrueba/ws_eprueba?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSEFactura.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "./ws_eprueba.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSEFactura(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSEFactura(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEFactura() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSEFactura(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSEFactura(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSEFactura(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSEFacturaSoapPort
     */
    @WebEndpoint(name = "WS_eFacturaSoapPort")
    public WSEFacturaSoapPort getWSEFacturaSoapPort() {
        return super.getPort(WSEFacturaSoapPort, WSEFacturaSoapPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSEFacturaSoapPort
     */
    @WebEndpoint(name = "WS_eFacturaSoapPort")
    public WSEFacturaSoapPort getWSEFacturaSoapPort(WebServiceFeature... features) {
        return super.getPort(WSEFacturaSoapPort, WSEFacturaSoapPort.class, features);
    }

}
