
package uy.gub.dgiConsulta;

import uy.gub.dgi.WSEFactura;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;
import com.antel.dti.sat.pcfv2.wsefacturaconsultaclient.WSEFacturaConsultasFactory;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-04/11/2011 03:11 PM(mockbuild)-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WS_eFactura_Consultas", targetNamespace = "http://dgi.gub.uy", wsdlLocation = "./ws_consultasPrueba.wsdl")
public class WSEFacturaConsultas
    extends Service
{
    private final static URL WSEFACTURACONSULTAS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(WSEFacturaConsultas.class.getName());

    static {
        URL url = WSEFactura.class.getResource("./ws_consultasPrueba.wsdl");
        if (url == null) {
            url = WSEFactura.class.getClassLoader().getResource("./ws_consultasPrueba.wsdl");
        }
        if (url == null) {
            Logger.getLogger(WSEFactura.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "./ws_consultasPrueba.wsdl");
        }
        WSEFACTURACONSULTAS_WSDL_LOCATION = url;
    }
    public WSEFacturaConsultas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSEFacturaConsultas() {
        super(WSEFACTURACONSULTAS_WSDL_LOCATION, new QName("http://dgi.gub.uy", "WS_eFactura_Consultas"));
    }

    /**
     * 
     * @return
     *     returns WSEFacturaConsultasSoapPort
     */
    @WebEndpoint(name = "WS_eFactura_ConsultasSoapPort")
    public WSEFacturaConsultasSoapPort getWSEFacturaConsultasSoapPort(boolean test) {
        String url = "";
        QName qname = null;
        if(test){
            url = "http://10.97.68.53:8087/dgiSimulator/ConsultasImpl"; /*CFB2Bn1 del ambiente DOCKER*/
            qname = new QName("http://dgi.gub.uy", "WS_eFactura_ConsultasSoapPort");
        }else{
           return WSEFacturaConsultasFactory.getWseFacturaConsultasSoapPort(); /*Si no es para DGISimulator le mando la solicitud al DGIConsumer*/
        }
        var port = super.getPort(qname, WSEFacturaConsultasSoapPort.class);
        var bp = (BindingProvider)port;
        bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, url);
        return port;
    }


}
